// Mocks generated by Mockito 5.4.4 from annotations
// in kura/test/services/medication_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:kura/src/services/firestore_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FirestoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreService<T> extends _i1.Mock
    implements _i2.FirestoreService<T> {
  MockFirestoreService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get collectionPath => (super.noSuchMethod(
        Invocation.getter(#collectionPath),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#collectionPath),
        ),
      ) as String);

  @override
  T Function(
    Map<String, dynamic>,
    String,
  ) get fromJson => (super.noSuchMethod(
        Invocation.getter(#fromJson),
        returnValue: (
          Map<String, dynamic> data,
          String documentId,
        ) =>
            _i3.dummyValue<T>(
          this,
          Invocation.getter(#fromJson),
        ),
      ) as T Function(
        Map<String, dynamic>,
        String,
      ));

  @override
  _i4.Future<void> create(
    T? data, [
    String? id,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [
            data,
            id,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<T?> get(String? id) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [id],
        ),
        returnValue: _i4.Future<T?>.value(),
      ) as _i4.Future<T?>);

  @override
  _i4.Stream<T?> getStream(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getStream,
          [id],
        ),
        returnValue: _i4.Stream<T?>.empty(),
      ) as _i4.Stream<T?>);

  @override
  _i4.Future<void> update(
    String? id,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [
            id,
            data,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<List<T>> getListStream() => (super.noSuchMethod(
        Invocation.method(
          #getListStream,
          [],
        ),
        returnValue: _i4.Stream<List<T>>.empty(),
      ) as _i4.Stream<List<T>>);
}
